/// Represents the response from an Auth0 MFA challenge initiation request.
///
/// This model encapsulates the server's response when requesting a multi-factor
/// authentication challenge, containing the information needed to complete
/// the MFA verification process.
///
/// Typical usage occurs after calling the Auth0 MFA challenge endpoint,
/// where this response provides:
/// - A unique challenge identifier
/// - Optional expiration information
/// - Optional human-readable messages
///
/// Example JSON Response:
/// ```json
/// {
///   "challenge_id": "xyz789...",
///   "expires_in": 300,
///   "message": "Enter the code sent to your device"
/// }
/// ```
class Auth0ChallengeResponse {
  /// The unique identifier for this MFA challenge.
  ///
  /// This ID must be preserved and included in subsequent verification requests.
  /// Typically a cryptographically random string generated by Auth0.
  ///
  /// Required field - will throw [FormatException] if missing from API response.
  final String challengeId;

  /// The time duration (in seconds) before this challenge expires.
  ///
  /// If provided, indicates how long the challenge remains valid.
  /// Common values:
  /// - 300 (5 minutes) for SMS/email codes
  /// - 600 (10 minutes) for push notifications
  ///
  /// When null, the challenge either doesn't expire or uses system defaults.
  final int? expiresIn;

  /// A human-readable message describing the challenge.
  ///
  /// Often contains instructions for the user about how to complete
  /// the MFA process (e.g., "Enter the 6-digit code sent to your phone").
  /// Can be safely displayed to end-users.
  final String? message;

  /// Creates an MFA challenge response instance.
  ///
  /// Parameters:
  /// - [challengeId]: Required unique challenge identifier
  /// - [expiresIn]: Optional validity duration in seconds
  /// - [message]: Optional user instructions
  Auth0ChallengeResponse({
    required this.challengeId,
    this.expiresIn,
    this.message,
  });

  /// Constructs an instance from a JSON map.
  ///
  /// Parses the response from Auth0's MFA challenge endpoint into a
  /// typed Dart object.
  ///
  /// Parameters:
  /// - [json]: The decoded JSON map from Auth0's API response
  ///
  /// Returns:
  /// A new [Auth0ChallengeResponse] instance
  ///
  /// Throws:
  /// - [FormatException] if required 'challenge_id' field is missing
  /// - Other [Exception] types for malformed data
  factory Auth0ChallengeResponse.fromJson(Map<String, dynamic> json) {
    if (json['challenge_id'] == null) {
      throw FormatException('Missing required field: challenge_id');
    }

    return Auth0ChallengeResponse(
      challengeId: json['challenge_id'] as String,
      expiresIn: json['expires_in'] as int?,
      message: json['message'] as String?,
    );
  }
}
